# Generated by Django 5.0.6 on 2024-06-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='licensenum',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
