# Generated by Django 5.0.6 on 2024-06-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_cars_licensenum_cars_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=50)),
                ('loction', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField(blank=True, max_length=10)),
            ],
        ),
    ]
