# Generated by Django 5.0.6 on 2024-06-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0003_showroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroom',
            name='zipcode',
            field=models.IntegerField(blank=True),
        ),
    ]
