# Generated by Django 5.0.6 on 2024-06-20 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0004_alter_showroom_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='showroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Showroom', to='Cars.showroom'),
        ),
    ]
